vicwomg/pikaraoke

app.py
This will prevent overwriting an existing song filename.
=> Prevent overwrite if filename exist

README.md, app.py, karaoke.py, static/custom.css, templates/home.html, vlcclient.py
=> Pitch Change support

karaoke.py
- Fix IP being returned as 127.0.0.1 with new ip detection routine
=> QR Code rendering Hostfile/dns vs DHCP IP #67

karaoke.py
=> #108 Recursively search subfolders for songs

karaoke.py
=> #110 Fix sorting for files from subfolders

README.md, constants.py, karaoke.py, templates/search.html
Hotfix for duplicate files showing in windows
=> #115 fix duplicate files in windows

setup-pi.sh
fix for apt installation python-pygame
=> fix: python-pygame name for apt installation

karaoke.py
Attempt 2 at fixing this issue
=> Web UI yt-dlp upgrader is not working #238

templates/search.html
Addressing this feature request https://github.com/vicwomg/pikaraoke/issues/343
=> Show search result as list

README.md, app.py, constants.py, karaoke.py, lib/get_platform.py, lib/vlcclient.py, pikaraoke.sh, setup-windows.bat, setup.sh, templates/info.html
Maintenance improvements:
- Improve ffmpeg debug logging
- Add more platform info to the logs and info screen for better bug reports
- force libx264 on pi 5 devices
- Prevent display errors when launching over SSH
- Fix issues with playing cdg files in recent pi-ffmpeg
- Add `git pull` to setup script to update codebase 
- Support more debian-based distros in setup script
=> Improve diagnostics and handle error conditions

app.py
Possible fix for issue mentioned in:
#355
=> Fix windows path mangling

.gitignore, .vscode/settings.json, code_quality/.pre-commit-config.yaml, code_quality/.vscode/settings.json, docs/README.md, docs/TROUBLESHOOTING.md, pikaraoke/app.py, pikaraoke/karaoke.py, poetry.lock, pyproject.toml
Experimental command line option `--normalize-audio` seems to work fine on my mac, but I imagine the pi will probably struggle to keep up. Testing needed
=> 342 volume normalization

pyproject.toml
missing long_description in build
=> fix(ci): missing long_description in build

pikaraoke/karaoke.py
break-system-packages in yt-dlp upgrade command
=> Yt dlp upgrade fix - simple

pikaraoke/app.py, pikaraoke/karaoke.py, pikaraoke/lib/get_platform.py, pikaraoke/templates/home.html, pikaraoke/templates/info.html
Fix for https://github.com/vicwomg/pikaraoke/issues/427
=> fix: Transposing hangs when ffmpeg does not have librubberband

pikaraoke/app.py, pikaraoke/templates/base.html
I've made some fixes:
On app.py: When the user wanted to delete a file that was already in queue the verification was flaw because it was like `if "file name" in queue` but the queue was a list of dictionary.
On base.html: The notifications when the page response was using flask flash wasn't showing.
=> Smal fixes

.gitignore, Dockerfile, docker/docker-compose.yml.example, docker/entrypoint.sh, pikaraoke/lib/get_platform.py, poetry.lock
Thanks to @jamalarm  and @honestlai for their contributions in getting this all running
=> feat: add dockerization support

docker/docker-compose.yml.example, pikaraoke/app.py, pikaraoke/karaoke.py, pikaraoke/lib/ffmpeg.py, pikaraoke/lib/file_resolver.py, pikaraoke/templates/files.html, pikaraoke/templates/splash.html, scripts/README.md
feat: run pikaraoke on a single port #303
=> feat: run pikaraoke on a single port #303

docker/docker-compose.yml.example, pikaraoke/app.py, pikaraoke/karaoke.py, pikaraoke/lib/ffmpeg.py, pikaraoke/lib/file_resolver.py, pikaraoke/templates/files.html, pikaraoke/templates/splash.html, scripts/README.md
Will only show the end timestamp if fully buffered flag is specified, since we can't calculate it otherwise
=> feat: add timestamp to splash screen

pikaraoke/translations/fr_FR/LC_MESSAGES/messages.po
Added french translations as stated in https://github.com/vicwomg/pikaraoke/wiki/Translation-help-needed!#help-translate-pikaraoke-to-more-languages.
=> docs: add french translation
